### ISSUE TITLE
Error in Firefox..

### ISSUE THREAD

**Issue by jeffconklin** [dmvaldman/samsara#27] opened 2016-02-12 19:48 UTC
Hello,

Nice plugin.

In Firefox (Ubuntu 14.04, FF v43.0.4), I receive the following error when I view any of your demos: TypeError: document.body is null, app.js : 4362 : 13

Here is a screen shot:
![screenshot from 2016-02-12 14 46 32](https://cloud.githubusercontent.com/assets/6152325/13018435/7c54dc2a-d197-11e5-9dd9-08ffc7ee67e7.png)

**Comment by dmvaldman** [comment] 2016-02-12 20:01
Interesting, I don't see that behavior in Firefox. Could you test one thing for me? In any of the demos in the `examples` folder, open the `index.html` in a text editor and move the following code to after the closing `</body>` tag

```
<script>
    require.config({
        paths: {
            samsara: '../../samsara'
        }
    });
    require(['js/main']);
</script>
```

And then open `index.html` in Firefox. Let me know if that fixes the problem for you. I'm guessing the script is executed before `document.body` is defined.

**Comment by jeffconklin** [comment] 2016-02-12 21:40
I just tried to open examples/SafariTabs/index.html and receive an entirely different error:

Error: Script error for: samsara/Streams/Stream
http://requirejs.org/docs/errors.html#scripterror

![screenshot from 2016-02-12 16 30 20](https://cloud.githubusercontent.com/assets/6152325/13020930/1a0f39c0-d1a6-11e5-8ba2-e6f5b66812e9.png)

![screenshot from 2016-02-12 16 39 43](https://cloud.githubusercontent.com/assets/6152325/13021107/3ef14fa2-d1a7-11e5-9fa8-7a225c279c47.png)

That kills the page/JS completely.

Also, I would assume that moving that code after the closing body tag would not help here. Your code is most likely looking for an element before it is available.

**Comment by dmvaldman** [comment] 2016-02-12 22:31
That's the purpose for the move. If the script is executed after the `body` is loaded, then `document.body` will be available.

All examples load on all browsers (Safari, Chrome, FF) on my machine.

**Comment by jeffconklin** [comment] 2016-02-19 00:11
Hello,

Sorry for the slow response here.

I think you missed the point of my last post. Your distribution is missing files. Moving the "require.config({" block anywhere on the page doesn't matter since something else in the example that you provided won't matter.

Secondly, if you are relying on someone to place your "require.config({" block into a specific place within their document, you should rethink how your plugin instantiates itself. The practice of putting any Javascript outside the head of not what the standards call for, but has become excepted by many as an acceptable practice. Placing anything between </body and </html is not something I would ever do in any page / project I am working on.

Anyways... I would be happy to test whatever you like. But, as mentioned, your examples don't work straight out the box. This is the third computer (1 Ubuntu, one Windows 7, one Windows 10) and they have all failed because of the missing file / error noted above.

**Comment by dmvaldman** [comment] 2016-02-19 14:53
Thanks for testing on all those operating systems! I'm asking for your help in testing (by moving the require call to after the body) only because I don't have access to the devices you're testing on. All the demos work out of the box on all the devices I've tested on (all browsers on OS X, Android 4.3+, iOS 7+), so I need to rely on others to test on devices I don't own.

**Comment by jeffconklin** [comment] 2016-02-19 16:06
I hate to sound rude here, but I don't know how else to tell you that what you provide in your examples is broken. Telling me that it works for you is not good support here. So here are more details:

What you have distributed does not work. I download your current ZIP file, extract it to my server(s), open the demo file in my browsers, and I receive those errors. To "prove" this, I have uploaded your entire project to:

getoutsidenj.com/temp/samsara-master/samsara-master/examples/SafariTabs/

In that example you will see the require block has been moved and I receive an error.

![screenshot from 2016-02-19 11 00 32](https://cloud.githubusercontent.com/assets/6152325/13180885/61ccd996-d6f8-11e5-878f-1bcf4a187827.png)

That was Chrome. Also, Chrome is saying that the Script tag outside the Body tag is invalid code.

![screenshot from 2016-02-19 11 05 33](https://cloud.githubusercontent.com/assets/6152325/13180983/c7fe7b5c-d6f8-11e5-9d69-9ff329679857.png)

I would like to help.

**Comment by bardu** [comment] 2016-02-19 16:47
@dmvaldman I believe on OSX file path isn't case sensitive, that's why it is working.
I went on my Ubuntu box and can confirm the issue of the OP.

> Uncaught Error: Script error for: samsara/Streams/Stream
http://requirejs.org/docs/errors.html#scripterror

As you can see in the script error there is a typo, the path to Stream is:

> samsara/streams/Stream

I didn't dick into the files where the typo is.
Hope that helps.

**Comment by dmvaldman** [comment] 2016-02-19 16:52
Thanks @bardu! Will fix

**Comment by bardu** [comment] 2016-02-19 17:01
@dmvaldman the typo is in TabContainer.js

**Comment by dmvaldman** [comment] 2016-02-19 17:02
Thanks, found it. This was the cause of the error in the SafariTabs example @jeffconklin. Still unsure of why the other demos aren't working for you.

**Comment by dmvaldman** [comment] 2016-02-19 17:05
Case-sensitivity bug fixed in 79fbd33d473f555082493ab868a6abcfb2d71057 and will be incorporated in the next release.

**Comment by bardu** [comment] 2016-02-19 17:09
@dmvaldman just to clarify: all the other demos work on Ubuntu. It was just the typo in the SafariTabs example.

**Comment by dmvaldman** [comment] 2016-02-19 17:12
Thanks for testing @bardu seems @jeffconklin has different results though, no?

**Comment by jeffconklin** [comment] 2016-02-20 22:04
Just downloaded your latest. SafariTabs is now working. And I can confirm that all of them are working in all my browsers on my Windows and Ubuntu boxes. Glad this could get worked out. Too bad I randomly picked the 1 demo with a different error to start. But they are all now working.

Keep up the good work.

**Comment by dmvaldman** [comment] 2016-02-20 23:33
Great. Thanks for your help.

**Closed by dmvaldman** 2016-02-20 23:33 UTC
